"""defined moon and planets relationships-one to many

Revision ID: 357c69319258
Revises: 75b7e4a65cee
Create Date: 2025-11-04 11:38:42.932352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357c69319258'
down_revision = '75b7e4a65cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'moons', ['moon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('moon_id')

    # ### end Alembic commands ###
